### ISSUE TITLE
Upsert WebPageSummary

### ISSUE THREAD

**Issue by moncapitaine** [progwise/george-ai#11]
Needs to:
- insert if LLM and URL are not present in CMS
- update if there is already a WebPageSummary with same LLM and URL

Question: How does it behave when updating if there was already a draft or already a published version?

**Comment by TonySchroeder** [comment]
- scrapePage function has been moved to its own file
- isValidLink function added to avoid repetition
- const urls and results have been removed
- first filtering of urlsTodo removed
- introduced a timeout of one minute for the page.goto function, in case the scrape takes too long
