### ISSUE TITLE
How to include chat history into similarity search?

### ISSUE THREAD

**Issue by moncapitaine** [progwise/george-ai#193]
- generate abstraction from the current history for similarity search
- send original question together with this abstraction to similarity search
- use this instead of only the question

**Comment by moncapitaine** [comment]
This would solve the problem:

1. Input from the user: Can you please plan a trip to to italy
- PDF search hits
- Tavily search hits
- answer

2. Oh no, I want to go in August 2025
... what does vector store and tavily do with this input... both don't know that we are talking about Tuscany here.
so we need a search term for similarity search and tavily search not only on the last user input but also including some history.

3. But with my mobile home (12 meters)
...same

**Comment by YohannesTesfay** [comment]
![Image](https://github.com/user-attachments/assets/8f847e77-3d9e-4b18-9538-0c5e795ad8bb)
