### ISSUE TITLE
Filter by keywords ?

### ISSUE THREAD

**Issue by TonySchroeder** [progwise/george-ai#66]
Facet = true in typesense for keywords
https://typesense.org/docs/0.20.0/api/collections.html#with-pre-defined-schema

- [ ] make keywords in the result list clickable
- [ ] If a user clicks on it, the keyword is printed in the header section
- [ ] The result is filtered for the same keyword
- [ ] Keyword in der header section can be removed again

**Comment by moncapitaine** [comment]
![Image](https://github.com/progwise/george-ai/assets/16672443/c1e075ba-59c0-4073-9442-8b8ef7456694)

**Comment by moncapitaine** [comment]
If you like you can introduce daisy....

**Comment by moncapitaine** [comment]
alternativ display all facets on the right side with some checkbox to filter for them. Facets are keywords?
