### ISSUE TITLE
Save scrape & chatGPT results as Strapi WebSiteSummary using strapi GraphQL

### ISSUE THREAD

**Issue by moncapitaine** [progwise/george-ai#7]
- [x] strapi websitesummary exists
- [x] graphql-request can call localhost:1337/graphql
- [x] graphql-request can call mutation for adding website summary
- [x] using codegen & graphql-request to access strapi graphql api using typescript => Tony

**Comment by PascalHelbig** [comment]
I think `urql` is an overhead here. We don't need a huge GraphQL client here. All we want to achieve is to send plain requests.

I think `graphql-request` is a much simpler lib with a tiny API: https://github.com/jasonkuhrt/graphql-request

It is also working in combination with GraphQL Codegen: https://the-guild.dev/graphql/codegen/plugins/presets/preset-client

@moncapitaine, what do you think?

**Comment by TonySchroeder** [comment]
Completed
